{"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/AsyncKit","doc:\/\/co.pointfree.VaporRouting\/documentation\/AsyncKit\/EventLoopFutureQueue","doc:\/\/co.pointfree.VaporRouting\/documentation\/AsyncKit\/EventLoopFutureQueue\/ContinueError"]]},"abstract":[{"text":"A previous future succeeded, which we don’t desire.","type":"text"}],"variants":[{"paths":["\/documentation\/asynckit\/eventloopfuturequeue\/continueerror\/previoussuccess"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/AsyncKit\/EventLoopFutureQueue\/ContinueError\/previousSuccess"},"sections":[],"metadata":{"symbolKind":"case","title":"EventLoopFutureQueue.ContinueError.previousSuccess","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousSuccess"}],"modules":[{"name":"AsyncKit"}],"roleHeading":"Case","externalID":"s:8AsyncKit20EventLoopFutureQueueC13ContinueErrorO15previousSuccessyA2EmF","role":"symbol"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Linux"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"previousSuccess","kind":"identifier"}]}]}],"references":{"doc://co.pointfree.VaporRouting/documentation/AsyncKit/EventLoopFutureQueue":{"kind":"symbol","title":"EventLoopFutureQueue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventLoopFutureQueue"}],"role":"symbol","abstract":[{"type":"text","text":"Allows you to queue closures that produce an "},{"type":"codeVoice","code":"EventLoopFuture"},{"type":"text","text":", so each future only gets run if the previous ones complete, succeed, or fail."}],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/AsyncKit\/EventLoopFutureQueue","url":"\/documentation\/asynckit\/eventloopfuturequeue","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EventLoopFutureQueue"}]},"doc://co.pointfree.VaporRouting/documentation/AsyncKit/EventLoopFutureQueue/ContinueError":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/AsyncKit\/EventLoopFutureQueue\/ContinueError","navigatorTitle":[{"text":"ContinueError","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/asynckit\/eventloopfuturequeue\/continueerror","abstract":[{"type":"text","text":"Errors that get propogated based on a future’s completion status and the next appended closure’s continuation condition."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContinueError","kind":"identifier"}],"role":"symbol","title":"EventLoopFutureQueue.ContinueError"},"doc://co.pointfree.VaporRouting/documentation/AsyncKit":{"abstract":[],"kind":"symbol","url":"\/documentation\/asynckit","role":"collection","title":"AsyncKit","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/AsyncKit","type":"topic"},"doc://co.pointfree.VaporRouting/documentation/AsyncKit/EventLoopFutureQueue/ContinueError/previousSuccess":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/AsyncKit\/EventLoopFutureQueue\/ContinueError\/previousSuccess","kind":"symbol","type":"topic","url":"\/documentation\/asynckit\/eventloopfuturequeue\/continueerror\/previoussuccess","abstract":[{"type":"text","text":"A previous future succeeded, which we don’t desire."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousSuccess","kind":"identifier"}],"role":"symbol","title":"EventLoopFutureQueue.ContinueError.previousSuccess"}}}