{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["Linux"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataReceivedInErrorState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ByteBuffer","preciseIdentifier":"s:7NIOCore10ByteBufferV","kind":"typeIdentifier","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteBuffer"},{"text":")","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/dataReceivedInErrorState(_:_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/niocore\/bytetomessagedecodererror\/datareceivedinerrorstate(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","abstract":[{"text":"More data has been received by a ","type":"text"},{"code":"ByteToMessageHandler","type":"codeVoice"},{"text":" despite the fact that an error has previously been","type":"text"},{"text":" ","type":"text"},{"text":"emitted. The associated ","type":"text"},{"code":"Error","type":"codeVoice"},{"text":" is the error previously emitted and the ","type":"text"},{"code":"ByteBuffer","type":"codeVoice"},{"text":" is the extra data that has","type":"text"},{"text":" ","type":"text"},{"text":"been received. The common cause for this error to be emitted is the user not having torn down the ","type":"text"},{"code":"Channel","type":"codeVoice"},{"text":" ","type":"text"},{"text":"after previously an ","type":"text"},{"code":"Error","type":"codeVoice"},{"text":" has been sent through the pipeline using ","type":"text"},{"code":"fireErrorCaught","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"roleHeading":"Case","symbolKind":"case","externalID":"s:7NIOCore25ByteToMessageDecoderErrorO014dataReceivedInF5StateyACs0F0_p_AA0B6BufferVtcACmF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataReceivedInErrorState"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:7NIOCore10ByteBufferV","text":"ByteBuffer"},{"kind":"text","text":")"}],"role":"symbol","modules":[{"name":"NIOCore"}],"title":"ByteToMessageDecoderError.dataReceivedInErrorState(_:_:)"},"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError"]]},"references":{"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteToMessageDecoderError":{"url":"\/documentation\/niocore\/bytetomessagedecodererror","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError","abstract":[{"text":"Common errors thrown by ","type":"text"},{"code":"ByteToMessageDecoder","type":"codeVoice"},{"type":"text","text":"s."}],"kind":"symbol","navigatorTitle":[{"text":"ByteToMessageDecoderError","kind":"identifier"}],"type":"topic","title":"ByteToMessageDecoderError","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ByteToMessageDecoderError","kind":"identifier"}]},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteToMessageDecoderError/dataReceivedInErrorState(_:_:)":{"type":"topic","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/dataReceivedInErrorState(_:_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataReceivedInErrorState"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ByteBuffer","preciseIdentifier":"s:7NIOCore10ByteBufferV"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"text":"More data has been received by a ","type":"text"},{"type":"codeVoice","code":"ByteToMessageHandler"},{"type":"text","text":" despite the fact that an error has previously been"},{"type":"text","text":" "},{"text":"emitted. The associated ","type":"text"},{"code":"Error","type":"codeVoice"},{"text":" is the error previously emitted and the ","type":"text"},{"code":"ByteBuffer","type":"codeVoice"},{"text":" is the extra data that has","type":"text"},{"text":" ","type":"text"},{"text":"been received. The common cause for this error to be emitted is the user not having torn down the ","type":"text"},{"code":"Channel","type":"codeVoice"},{"text":" ","type":"text"},{"text":"after previously an ","type":"text"},{"code":"Error","type":"codeVoice"},{"text":" has been sent through the pipeline using ","type":"text"},{"code":"fireErrorCaught","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/niocore\/bytetomessagedecodererror\/datareceivedinerrorstate(_:_:)","title":"ByteToMessageDecoderError.dataReceivedInErrorState(_:_:)"},"doc://co.pointfree.VaporRouting/documentation/NIOCore":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore","role":"collection","kind":"symbol","type":"topic","abstract":[],"title":"NIOCore","url":"\/documentation\/niocore"},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteBuffer":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ByteBuffer"}],"url":"\/documentation\/niocore\/bytebuffer","title":"ByteBuffer","kind":"symbol","type":"topic","abstract":[{"type":"codeVoice","code":"ByteBuffer"},{"type":"text","text":" stores contiguously allocated raw bytes. It is a random and sequential accessible sequence of zero or"},{"type":"text","text":" "},{"type":"text","text":"more bytes (octets)."}],"navigatorTitle":[{"kind":"identifier","text":"ByteBuffer"}],"role":"symbol","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteBuffer"}}}